### ISSUE TITLE
CGNS HDF5 configuration

### ISSUE THREAD

**Issue by m-kurz** [hopr-framework/hopr#10] opened 2021-09-14 20:47 UTC
Enabling HDF5 CGNS support in pull Request #4 broke the CGNS building process inside HOPR for me. I used standard Cmake flags except using the prebuilt HDF5 and
- openmpi 4.1.1
- hdf5/1.12.1
- CMake 3.21.2
- gcc 10.3 / gcc 9.3

which are the standard modules on Siegfried. The building process fails with:
```
  CMake Error at CMakeLists.txt:210 (add_executable):
  add_executable cannot create imported target "h5dump" because another
  target with the same name already exists.
```
If the Cmake flag for CGNS is set again to `-DCGNS_ENABLE_HDF5=OFF`, everything works fine for me.

Does someone else also have this issue?

**Comment by kopperp** [comment] 2021-09-15 08:31
The modules you mention do not appear to be available to me. I cannot reproduce the same issue using the module combination
- gcc 10.2
- cmake 3.18.4
- openmpi 4.1.1
- hdf5 1.12.0

However, I ran into the issue that CMake would configure, but CGNS does not build because of
```
[ 10%] Building C object src/CMakeFiles/cgns_static.dir/cgns_internals.c.o
In file included from /opt/spack/opt/spack/linux-ubuntu18.04-zen2/gcc-10.2.0/hdf5-1.12.0-5m74fk75xvjzdhbh3hiyzbxqdcqbp67b/include/hdf5.h:22,
                 from /home/iagkopper/Git/hopr/hopr-project/share/GNU/CGNS/build/src/cgns/src/cgns_internals.c:38:
/opt/spack/opt/spack/linux-ubuntu18.04-zen2/gcc-10.2.0/hdf5-1.12.0-5m74fk75xvjzdhbh3hiyzbxqdcqbp67b/include/H5public.h:63:13: fatal error: mpi.h: No such file or directory
   63 | #   include <mpi.h>
      |             ^~~~~~~
compilation terminated.
src/CMakeFiles/cgns_static.dir/build.make:94: recipe for target 'src/CMakeFiles/cgns_static.dir/cgns_internals.c.o' failed
make[5]: *** [src/CMakeFiles/cgns_static.dir/cgns_internals.c.o] Error 1
CMakeFiles/Makefile2:172: recipe for target 'src/CMakeFiles/cgns_static.dir/all' failed
make[4]: *** [src/CMakeFiles/cgns_static.dir/all] Error 2
Makefile:170: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/cgns.dir/build.make:129: recipe for target '../share/GNU/CGNS/build/src/cgns-stamp/cgns-build' failed
make[2]: *** [../share/GNU/CGNS/build/src/cgns-stamp/cgns-build] Error 2
CMakeFiles/Makefile2:270: recipe for target 'CMakeFiles/cgns.dir/all' failed
make[1]: *** [CMakeFiles/cgns.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
```
The culprit seems to be the `-DCGNS_ENABLE_HDF5=ON` in [CMakeListsLib.txt:284](https://github.com/hopr-framework/hopr/commit/1910a371d856648777b74a3f632e5d7f85bd71a2#diff-d507b571581b76f45a22d95269d6ade7b90e12a8596ca6bec5089ab5a0e1c11eR284). I'm not sure why it needed to be enabled and it does not tell in #4. Maybe @pnizenkov can clarify?

**Comment by m-kurz** [comment] 2021-09-15 08:46
Interesting. I also get your error message when trying to compile with
- gcc 7.5.0
- hdf5 1.10.4
- openmpi 3.1.3.
- cmake 3.10.2
These might be different problems? However, in both cases, the errors disappear once the HDF5 support of CGNS is disabled.

**Comment by kopperp** [comment] 2021-09-15 09:09
After your help I was able to find the same modules as you did and can now reproduce your error. I agree that these might represent different problems but in either case, it seems both are upstream bugs. `h5dump` is not added by us but instead I can see the double `add_executable` inside CGNS (line 210 and 256). Either this or the different `set_property` are most likely the culprit to me.
```bash
$ search 'h5dump' ./share
./share/GNU/CGNS/build/src/cgns/CMakeLists.txt:210:    add_executable (h5dump IMPORTED)
./share/GNU/CGNS/build/src/cgns/CMakeLists.txt:223:        set_property (TARGET h5dump PROPERTY IMPORTED_LOCATION "${HDF5_TOOLS_DIR}/h5dumpdll")
./share/GNU/CGNS/build/src/cgns/CMakeLists.txt:225:        set_property (TARGET h5dump PROPERTY IMPORTED_LOCATION "${HDF5_TOOLS_DIR}/h5dump")
./share/GNU/CGNS/build/src/cgns/CMakeLists.txt:233:      set_property (TARGET h5dump PROPERTY IMPORTED_LOCATION "${HDF5_TOOLS_DIR}/h5dump")
./share/GNU/CGNS/build/src/cgns/CMakeLists.txt:235:    set (HDF5_DUMP_EXECUTABLE $<TARGET_FILE:h5dump>)
./share/GNU/CGNS/build/src/cgns/CMakeLists.txt:256:    add_executable (h5dump IMPORTED)
./share/GNU/CGNS/build/src/cgns/CMakeLists.txt:257:    set_property (TARGET h5dump PROPERTY IMPORTED_LOCATION "${HDF5_TOOLS_DIR}/h5dump")
./share/GNU/CGNS/build/src/cgns/CMakeLists.txt:258:    set (HDF5_DUMP_EXECUTABLE $<TARGET_FILE:h5dump>)
```

To be honest, the entire IF-structure appears weird to me since it is effectively the following.
```CMake
  if (HDF5_FOUND)
    add_executable (h5dump IMPORTED)
    [...]
      if (BUILD_SHARED_LIBS AND WIN32)
        set_property (TARGET h5dump PROPERTY IMPORTED_LOCATION "${HDF5_TOOLS_DIR}/h5dumpdll")
      else (BUILD_SHARED_LIBS AND WIN32)
        set_property (TARGET h5dump PROPERTY IMPORTED_LOCATION "${HDF5_TOOLS_DIR}/h5dump")
      endif (BUILD_SHARED_LIBS AND WIN32)
    [...]
  else (HDF5_FOUND)
    [...]
    add_executable (h5dump IMPORTED)
    set_property (TARGET h5dump PROPERTY IMPORTED_LOCATION "${HDF5_TOOLS_DIR}/h5dump")
    [...]
  endif (HDF5_FOUND)
```
I do agree that CMake should not enter the `else` parts but I cannot see why they are there in the first place. However, the entire problem might be already fixed upstream since we are explicitly requesting version `3.4.1` instead of the current `4.2.0`, see commit [1b96135](https://github.com/hopr-framework/hopr/commit/1b9613539bf31887d04eee0fc726373031533919).

**Comment by m-kurz** [comment] 2021-09-15 12:16
Adding `-DHDF5_NEED_MPI=ON` to the CGNS cmake flags solved these issues for me, at least on most systems. However, I'm not sure what happens if he tries to link against serial HDF5.

**Comment by pnizenkov** [comment] 2021-09-24 09:18
> The culprit seems to be the `-DCGNS_ENABLE_HDF5=ON` in [CMakeListsLib.txt:284](https://github.com/hopr-framework/hopr/commit/1910a371d856648777b74a3f632e5d7f85bd71a2#diff-d507b571581b76f45a22d95269d6ade7b90e12a8596ca6bec5089ab5a0e1c11eR284). I'm not sure why it needed to be enabled and it does not tell in #4. Maybe @pnizenkov can clarify?

It is required to be able to open CGNS files, which were exported using the HDF5 data structure instead of the old ADF structure.  One of our grid generators (OMNIS/Hexpress) stopped offering the possibility to chose between CGNS (ADF) and CGNS (HDF) export. 

On a side note: I did not have problems with CGNS installation and the h5dump error, when using the configure command instead of cmake to build HDF5.

**Comment by kopperp** [comment] 2021-09-29 13:14
Thanks for the clarification, that's actually a nice feature to have. If we build HDF5 with HOPR, we indeed use the `configure` path, see [https://github.com/hopr-framework/hopr/blob/master/CMakeListsLib.txt#L163](https://github.com/hopr-framework/hopr/blob/master/CMakeListsLib.txt#L163). This approach is e.q. shared by Arch Linux, including some [interesting comment](https://github.com/archlinux/svntogit-community/blob/packages/hdf5/trunk/PKGBUILD#L22).

Unfortunately, at least spack follows the [CMake path](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/hdf5/package.py#L13), probably leaving some leftover properties and breaking our CMake build. The best way would be probably to just clear the target before we call the CGNS build, but I am yet to find a way to do so.

**Comment by scopplestone** [comment] 2023-02-06 12:27
With the lasted release this issue should be resolved. Closing the thread. If there are still problems, re-open the issue.

**Closed by scopplestone** 2023-02-06 12:27 UTC
Labels: bug
